version: '3.3'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - ./project:/usr/src/app
      - /home/ubuntu/cert.pem:/app/cert.pem
      - /home/ubuntu/private_key.pem:/app/key.pem
    ports:
      - 8002:8000
      #- 443:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DOMAIN=ml.fipointer.com
      - CERT_PATH=/app/cert.pem
      - KEY_PATH=/app/key.pem
      - DATABASE_URL=postgres://shuchiagarwal:nakul300@web-db:5432/shuchiagarwal
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  volumes:
      db_data:

    environment:
      - POSTGRES_USER=shuchiagarwal
      - POSTGRES_PASSWORD=nakul300

  frontend:
    build:
      context: ./project/frontend
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - web
    volumes:
        - ./project:/usr/src/app
    environment:
      PYTHONUNBUFFERED: '1'        
